server:
  port: 1234

spring:
  application:
    name: inventory-api
    
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: never
    password: project2
    username: hermeslisoma
    url: jdbc:postgresql://hermeslisoma.cvnmtqur08tc.us-east-2.rds.amazonaws.com:5432/hermeslisoma
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate: 
        default_schema: inv
    show-sql: false
