server:
  port: 1234

spring:
  application:
    name: school-api
    
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: never
    password: Ernesto13
    username: ernesto
    url: jdbc:postgresql://sample.ce2jzqfksskd.us-east-2.rds.amazonaws.com:5432/sampledb
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate: 
        default_schema: project2
    show-sql: false  

          